name: Documentation

on:
  push:
    branches: [ main ]
    paths:
      - '**.go'
      - 'README.md'
      - '.github/workflows/docs.yml'

jobs:
  godoc:
    name: Generate Go Documentation
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Install godoc
      run: go install golang.org/x/tools/cmd/godoc@latest

    - name: Generate documentation
      run: |
        # Start godoc server in background
        godoc -http=:6060 &
        GODOC_PID=$!
        
        # Wait for server to start
        sleep 5
        
        # Generate static documentation
        mkdir -p docs
        curl -s http://localhost:6060/pkg/github.com/murilopl/go-mem0/client/ > docs/client.html
        
        # Kill godoc server
        kill $GODOC_PID
        
        echo "Documentation generated in docs/"

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        publish_branch: gh-pages
        force_orphan: true